#!/usr/bin/env perl

use strict;
use warnings;
use Cwd;

my $response;
my $current_dir = cwd(); # Get current working directory
$current_dir .= "/zephyrproject";

# Start navigation from 'zephyrproject'
chdir("zephyrproject") or die "Failed to enter 'zephyrproject': $!\n";

# Ask weather the user would like flash the application or not and
# reactivate virtual environment approriately.

while (1) {
    print "Would you like to flash the current application to the specified board? (yes/no): ";
    chomp($response = <STDIN>);
    $response = lc($response);  # Normalize to lowercase

    if ($response eq 'yes') {
        print "Flashing the application...\n";
        system("bash -c '
        source $current_dir/.venv/bin/activate && cd $current_dir &&
        west flash --build-dir zephyr/build/ && deactivate'") == 0
            or die "Failed to flash the board: $!";
        print "Flash successful!\n";
        last;
    } elsif ($response eq 'no') {
        print "Flash operation skipped.\n";
        last;
    } elsif ($response eq 'y') {
        print "Please type the full word 'yes' or 'no'.\n";
    } else {
        print "Invalid input. Please respond with 'yes' or 'no'.\n";
    }
}
