#!/usr/bin/perl
use strict;
use warnings;
#commands to activate zephyr virtual environment and build zephyr project:
#python3 -m venv /home/aharfuch/Kernergetiks/Humidity-control/zephyrproject/.venv
#source /home/aharfuch/Kernergetiks/Humidity-control/zephyrproject/.venv/bin/activate
#pip install west
#west update
#west packages pip --install
#west sdk install
#west build -p always -b nrdf7002dk/nrf5340/cpuapp <$path> #$path is where the source code is

# Step 1: Create the Python virtual environment
my $venv_name = "../.venv";
my $status = system("python3 -m venv $venv_name");
die "Failed to create virtual environment!\n" if $status != 0;

# Step 2: Activate virtual environment and install dependencies
$status = system("bash -c 'source $venv_name/bin/activate && pip install west && west update && west zephyr-export && west packages pip --install && west sdk install && west build -p always -b nrf7002dk/nrf5340/cpuapp src/fan_pwm'");
print "West has been installed\n";
